name: hello-world
on:
  workflow_dispatch:
    inputs:
      enviroment:
        type: choice
        description: Pick Enviroment
        options:
        - Dev
        - Test
        - Stage
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World! '${{ github.event.inputs.enviroment }}'"
